<?php

namespace CSRU\CSRUBundle\Repository;

/**
 * Carte_AMVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Carte_AMVRepository extends \Doctrine\ORM\EntityRepository
{
   
}

