<?php

namespace CSRU\CSRUBundle\Repository;

/**
 * CentreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentreRepository extends \Doctrine\ORM\EntityRepository
{
     public function getStatistiqueCENTRE() {
  
        return $this->createQueryBuilder('g')
                ->leftJoin('g.centre', 'c')
                        ->addselect('c')
                        ->where('c.nom = :u')
                        ->setParameter('u','CSRU FST')
                        ->getQuery()
                         ->getResult();
  
    }
}

