<?php

namespace CSRU\CSRUBundle\Repository;

/**
 * ConsultationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultationRepository extends \Doctrine\ORM\EntityRepository
{
   
}

