<?php

namespace CSRU\CSRUBundle\Repository;

/**
 * DossierMedicalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierMedicalRepository extends \Doctrine\ORM\EntityRepository {

    public function getPatient($data) {
        $query = $this->createQueryBuilder('p')
           ->leftJoin('p.etudiant', 'e')
            ->addSelect('e')
            ->where("e.matricule LIKE :cher")
            ->setParameter('cher', '%'.$data.'%')
            ->getQuery();
        return $query->getResult();
    }

    public function getStatistiqueHomme() {
  
        return $this->createQueryBuilder('g')
                ->leftJoin('g.etudiant', 'e')
                        ->addselect('e')
                        ->where('e.genre = :a')
                        ->setParameter('a','Masculin')
                        ->getQuery()
                        ->getResult();
    }
    public function getStatistiqueFemme() {
  
        return $this->createQueryBuilder('g')
                ->leftJoin('g.etudiant', 'e')
                        ->addselect('e')
                        ->where('e.genre = :a')
                        ->setParameter('a','Féminin')
                        ->getQuery()
                        ->getResult();
  
    }
    
     public function getStatistiqueUSTTB() {
  
        return $this->createQueryBuilder('g')
                ->leftJoin('g.etudiant', 'e')
                        ->addselect('e')
                        ->where('e.universite = :u')
                        ->setParameter('u','USTTB')
                        ->getQuery()
                        ->getResult();
  
    }
    
    public function getStatistiqueUSSGB() {
  
        return $this->createQueryBuilder('g')
                ->leftJoin('g.etudiant', 'e')
                        ->addselect('e')
                        ->where('e.universite = :u')
                        ->setParameter('u','USSGB')
                        ->getQuery()
                        ->getResult();
  
    }
    
    public function getStatistiqueUSJPB() {
  
        return $this->createQueryBuilder('g')
                ->leftJoin('g.etudiant', 'e')
                        ->addselect('e')
                        ->where('e.universite = :u')
                        ->setParameter('u','USJPB')
                        ->getQuery()
                        ->getResult();
  
    }
    
     public function getStatistiqueULSHB() {
  
        return $this->createQueryBuilder('g')
                ->leftJoin('g.etudiant', 'e')
                        ->addselect('e')
                        ->where('e.universite = :u')
                        ->setParameter('u','ULSHB')
                        ->getQuery()
                        ->getResult();
  
    }
     public function getStatistiqueUS() {
  
        return $this->createQueryBuilder('g')
                ->leftJoin('g.etudiant', 'e')
                        ->addselect('e')
                        ->where('e.universite = :u')
                        ->setParameter('u','US')
                        ->getQuery()
                        ->getResult();
  
    }
    
}
