<?php

namespace CSRU\CSRUBundle\Repository;

/**
 * ExamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenRepository extends \Doctrine\ORM\EntityRepository
{
   
}

