<?php

namespace CSRU\CSRUBundle\Repository;

/**
 * FicheSortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheSortieRepository extends \Doctrine\ORM\EntityRepository {

    
}
