<?php

namespace CSRU\CSRUBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find all forums
     *
     * @param int $page
     * @param int $max
     * @return Paginator
     */
    public function findAll($page =1, $max= 4)
    {
    $qb = $this->createQueryBuilder('p');
    $qb->setFirstResult(($page-1) * $max)
    ->setMaxResults($max);
    return new Paginator($qb, true);
    }
}

