<?php

namespace CSRU\CSRUBundle\Repository;

/**
 * MedicamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicamentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMediFst($data)
    {
        $query = $this->createQueryBuilder('p')
            ->where("p.nom LIKE :cher")
            ->setParameter('cher', '%'.$data.'%')
            ->getQuery();
        return $query->getResult();
    }
    
    
    public function getMediIpr($data)
    {
        $query = $this->createQueryBuilder('p')
            ->where("p.nom LIKE :cher")
            ->setParameter('cher', '%'.$data.'%')
            ->getQuery();
        return $query->getResult();
    }
    
     public function getMediSegou($data)
    {
        $query = $this->createQueryBuilder('p')
            ->where("p.nom LIKE :cher")
            ->setParameter('cher', '%'.$data.'%')
            ->getQuery();
        return $query->getResult();
    }
    
}

