<?php

namespace CSRU\CSRUBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
     public function getStatistiqueCentreFST() {
  
        return $this->createQueryBuilder('u')
                ->leftJoin('u.profil', 'p')
                        ->addselect('p')
                        ->where('p.centre = :c')
                        ->setParameter('c','CSRU FST')
                        ->getQuery()
                        ->getResult();
  
    }
    
     public function getStatistiqueCentreIPR() {
  
        return $this->createQueryBuilder('u')
                ->leftJoin('u.profil', 'p')
                        ->addselect('p')
                        ->where('p.centre = :c')
                        ->setParameter('c','CSRU IPR')
                        ->getQuery()
                        ->getResult();
  
    }
    
     public function getStatistiqueCentreSEGOU() {
  
        return $this->createQueryBuilder('u')
                ->leftJoin('u.profil', 'p')
                        ->addselect('p')
                        ->where('p.centre = :c')
                        ->setParameter('c','CSRU SEGOU')
                        ->getQuery()
                        ->getResult();
    }
    
    public function getStatistiqueCentreCENOU() {
  
        return $this->createQueryBuilder('u')
                ->leftJoin('u.profil', 'p')
                        ->addselect('p')
                        ->where('p.centre = :c')
                        ->setParameter('c','CENOU')
                        ->getQuery()
                        ->getResult();
    }
    
     public function getStatistiqueProfInfirmier() {
  
        return $this->createQueryBuilder('u')
                ->leftJoin('u.profil', 'p')
                        ->addselect('p')
                        ->where('p.profession = :n')
                        ->setParameter('n','Infirmier')
                        ->getQuery()
                        ->getResult();
    }
    
    public function getStatistiqueProfPrestataire() {
  
        return $this->createQueryBuilder('u')
                ->leftJoin('u.profil', 'p')
                        ->addselect('p')
                        ->where('p.profession = :n')
                        ->setParameter('n','Prestataire')
                        ->getQuery()
                        ->getResult();
    }
    
    public function getStatistiqueProfAdmin() {
  
        return $this->createQueryBuilder('u')
                ->leftJoin('u.profil', 'p')
                        ->addselect('p')
                        ->where('p.profession = :n')
                        ->setParameter('n','Administrateur')
                        ->getQuery()
                        ->getResult();
    }
}

