services:
#    csrucsru.example:
#        class: CSRU\CSRUBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    csru_csru.registration_listener:
        class: CSRU\CSRUBundle\Listener\RegistrationListener
        tags:
            - { name: kernel.event_listener, event: fos_user.registration.completed, method: onKernelResponse, priority: 255 }
